### PR TITLE
fixed webhook vulnerability

### LINKED ISSUE #3: Discord Webhook is Exposed

### PR DESCRIPTION
**Pull request by Hunter-The-Great**
closes #3

### CODE REVIEW

**Comment by cssmith8** [comment]
I approve

File: website/src/env.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ export const env = createEnv({
     PUBLIC_URL: z.string().url(),
     GOOGLE_CLIENT_ID: z.string(),
     GOOGLE_CLIENT_SECRET: z.string(),
+    DISCORD_WEBHOOK: z.string(),
```
Comment (drew-harris) [inline website/src/env.ts]: change to DISCORD_WEBHOOK_URL to be more consistent with other url based envrionment variables

**Review by drew-harris — CHANGES_REQUESTED** [review]

**Review by drew-harris — APPROVED** [review]
